newArray = mymap(nums, double);
console.log(newArray);
console.log(nums);
let a = window.app;
a.increment();
a.increment();
a.increment();
a.increment();
a.increment();
a.increment();
a.increment();
a.increment();
a.increment();
a.increment();
console.log(a.getCount());
count1 = window.app.newCount();
count2 = window.app.newCount();
count1.increment();
count1.increment();
count1.increment();
count1.increment();
count1.increment();
console.log(count1.getCount());
count2.increment();
count2.increment();
count2.increment();
count2.increment();
count2.increment();
count2.increment();
count2.increment();
count2.increment();
count2.increment();
count2.increment();
count2.increment();
count2.increment();
count2.increment();
count2.increment();
count2.increment();
console.log(count2.getCount());
console.log(count2.getNumOfCount());

